service: caniuse-scraper
provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: eu-west-1
  memorySize: 128
functions:
  app:
    handler: main/app.handler
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true